#%RAML 1.0 Trait
400:
  body:
    application/json:
      example:
          {
            "Message": "Bad request"
          } 
500:
  body:
    application/json:
      example:
              {"Message":"Internal server error"}